config/routes.rb
Rails.application.routes.draw do
  resource :registration
  resource :session

  resources :articles
  resources :projects
  resources :investments
  resources :podcasts
  resources :books
  resources :toys
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :slug, :body, :publish_at, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/investment.rb
class Investment < ApplicationRecord
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  validates :name, :link, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :slug, :year, :description, :outcome, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many_attached :images

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  normalizes :email, with: -> (email) { email.strip.downcase }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.order(publish_at: :desc)
  end

  def show
    @article = Article.find_by(slug: params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find_by(slug: params[:id])
  end

  def update
    @article = Article.find_by(slug: params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    Article.find_by(slug: params[:id]).destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :slug, :body, :publish_at)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @fiction = Book.where(category: "Fiction").order(title: :asc)
    @nonfiction = Book.where(category: "Nonfiction").order(title: :asc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(slug: params[:id])

    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :link, :category)
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @investments = Investment.all.order(year: :desc)
  end

  def new
    @investment = Investment.new
  end

  def create
    @investment = Investment.new(investment_params)
    if @investment.save
      redirect_to investments_path
    else
      render :new
    end
  end

  def edit
    @investment = Investment.find_by(id: params[:id])
  end

  def update
    @investment = Investment.find_by(id: params[:id])
    if @investment.update(investment_params)
      redirect_to investments_path
    else
      render :edit
    end
  end

  def destroy
    @investment = Investment.find_by(id: params[:id])
    @investment.destroy
    redirect_to investments_path
  end

  private

  def investment_params
    params.require(:investment).permit(:company, :link, :year, :amount, :about, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @podcasts = Podcast.all.order(name: :asc)
  end

  def new
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new(podcast_params)

    if @podcast.save
      redirect_to podcasts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @podcast = Podcast.find(params[:id])
  end

  def update
    @podcast = Podcast.find(params[:id])

    if @podcast.update(podcast_params)
      redirect_to podcasts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy
    redirect_to podcasts_path
  end

  private

  def podcast_params
    params.require(:podcast).permit(:name, :link)
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @toys = Toy.all.order(:platform, :name)
  end

  def new
    @toy = Toy.new
  end

  def show
    @toy = Toy.find_by(id: params[:id])
    @full_width = true
  end

  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to @toy
    else
      render :new
    end
  end

  private

  def toy_params
    params.require(:toy).permit(:name, :description, :artist, :manufacturer, :release_date, :size, :platform, :color, :series, :original_price, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_symbol
    symbols = %w[⦂⦂ ⦿ ⊛ ⊚ ⊙ ⦚ ⟁ ⦂⦚ ⌇ ⦚⦚ ⌁ ⌀ ⌮ ⌬ ⌭ ⌯ ⌰ ⌱ ⌲ ⌳ ⌴ ⌵ ⌽ ⌾ ⌿ ⍀ ⍅ ⍆ ⍉ ⍊ ⍋ ⍎ ⍏ ⍑ ⍒ ⍕ ⍖ ⍘ ⍙ ⍚ ⍛ ⍜ ⍝ ⍡ ⍢ ⍣ ⍤ ⍥ ⍦ ⍧ ⍨ ⍩ ⍪ ⍫ ⍬ ⍭ ⍮ ⍱ ⍲ ⍻ ⍼ ⍽ ⍾ ⍿ ⟀ ⟁ ⟂ ⟃ ⟄ ⟅ ⟆ ⟇ ⟈ ⟉ ⟊ ⟌ ⟐ ⟑ ⟒ ⟓ ⟔]
    symbols.sample
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      space_after_headers: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def description(page_description)
    content_for(:description) { page_description }
  end

  def meta_image(meta_image)
    content_for(:meta_image) { meta_image }
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/investments/_form.html.erb
<%= form_with model: @investment do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div class="mb-4">
    <%= form.label :company, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :company, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :link, class: "block text-sm font-bold mb-2" %>
    <%= form.url_field :link, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :year, class: "block text-sm font-bold mb-2" %>
    <%= form.number_field :year, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :amount, class: "block text-sm font-bold mb-2" %>
    <%= form.number_field :amount, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0", step: 0.01 %>
  </div>

  <div class="mb-4">
    <%= form.label :about, class: "block text-sm font-bold mb-2" %>
    <%= form.text_area :about, rows: 5, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>  

  <div class="flex items-center justify-between">
    <%= form.submit form.object.new_record? ? "Add Investment" : "Update Investment", class: "bg-gold-500 hover:bg-gold-600 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/investments/index.html.erb
<% title "Investments" %>

<div class="flex items-start">
  <h1 class="font-serif text-4xl">Investments</h1>
  <% if user_signed_in? %>
    <span class="mt-2 ml-4"><%= link_to 'Add New Investment', new_investment_path %></span>
  <% end %>
</div>
<p class="mt-0 text-lg">I've been doing tiny investments in startups since 2021, primarily to just get my feet wet and to diversify my high-level personal finance holdings. Here are the investments I've made.</p>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Year</th>
      <th>Amount</th>
      <th>About</th>
    </tr>
  </thead>
  <tbody class="text-sm">
    <% @investments.each do |investment| %>
      <tr>
        <td class="px-2 py-3"><%= link_to investment.company, investment.link, class: "thick-link" %></td>
        <td><%= investment.year %></td>
        <td><%= number_to_currency(investment.amount, precision: 0) %></td>
        <td><%= investment.about %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/investments/new.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Investments', investments_path %>
  </nav>
  <h1 class="font-serif text-4xl">Add a new investment</h1>
</div>

<%= render 'form', investment: @investment %>