config/routes.rb
Rails.application.routes.draw do
  resource :registration
  resource :session

  resources :articles
  resources :projects
  resources :investments
  resources :podcasts
  resources :books
  resources :toys
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :slug, :body, :publish_at, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/investment.rb
class Investment < ApplicationRecord
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  validates :name, :link, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :slug, :year, :description, :outcome, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many_attached :images

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  normalizes :email, with: -> (email) { email.strip.downcase }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.order(publish_at: :desc)
  end

  def show
    @article = Article.find_by(slug: params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find_by(slug: params[:id])
  end

  def update
    @article = Article.find_by(slug: params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    Article.find_by(slug: params[:id]).destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :slug, :body, :publish_at)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @fiction = Book.where(category: "Fiction").order(title: :asc)
    @nonfiction = Book.where(category: "Nonfiction").order(title: :asc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(slug: params[:id])

    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :link, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @podcasts = Podcast.all.order(name: :asc)
  end

  def new
    @podcast = Podcast.new
  end

  def create
    @podcast = Podcast.new(podcast_params)

    if @podcast.save
      redirect_to podcasts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @podcast = Podcast.find(params[:id])
  end

  def update
    @podcast = Podcast.find(params[:id])

    if @podcast.update(podcast_params)
      redirect_to podcasts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy
    redirect_to podcasts_path
  end

  private

  def podcast_params
    params.require(:podcast).permit(:name, :link)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order(year: :asc)
    @full_width = true
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find_by(slug: params[:id])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project created successfully."
      redirect_to projects_path
    else
      flash.now[:alert] = "Project could not be created."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find_by(slug: params[:id])
  end

  def update
    @project = Project.find_by(slug: params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project updated successfully."
      redirect_to projects_path
    else
      flash.now[:alert] = "Project could not be updated."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find_by(slug: params[:id])
    if @project.destroy
      flash[:notice] = "Project deleted successfully."
      redirect_to projects_path
    else
      flash.now[:alert] = "Project could not be deleted."
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :slug, :link, :description, :outcome, :notes, :year)
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @toys = Toy.all.order(:platform, :name)
  end

  def new
    @toy = Toy.new
  end

  def show
    @toy = Toy.find_by(id: params[:id])
    @full_width = true
  end

  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to @toy
    else
      render :new
    end
  end

  private

  def toy_params
    params.require(:toy).permit(:name, :description, :artist, :manufacturer, :release_date, :size, :platform, :color, :series, :original_price, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_symbol
    symbols = %w[⦂⦂ ⦿ ⊛ ⊚ ⊙ ⦚ ⟁ ⦂⦚ ⌇ ⦚⦚ ⌁ ⌀ ⌮ ⌬ ⌭ ⌯ ⌰ ⌱ ⌲ ⌳ ⌴ ⌵ ⌽ ⌾ ⌿ ⍀ ⍅ ⍆ ⍉ ⍊ ⍋ ⍎ ⍏ ⍑ ⍒ ⍕ ⍖ ⍘ ⍙ ⍚ ⍛ ⍜ ⍝ ⍡ ⍢ ⍣ ⍤ ⍥ ⍦ ⍧ ⍨ ⍩ ⍪ ⍫ ⍬ ⍭ ⍮ ⍱ ⍲ ⍻ ⍼ ⍽ ⍾ ⍿ ⟀ ⟁ ⟂ ⟃ ⟄ ⟅ ⟆ ⟇ ⟈ ⟉ ⟊ ⟌ ⟐ ⟑ ⟒ ⟓ ⟔]
    symbols.sample
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      space_after_headers: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def description(page_description)
    content_for(:description) { page_description }
  end

  def meta_image(meta_image)
    content_for(:meta_image) { meta_image }
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :slug, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :slug, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :body, class: "block text-sm font-bold mb-2" %>
    <%= form.text_area :body, rows: 10, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :publish_at, class: "block text-sm font-bold mb-2" %>
    <%= form.datetime_field :publish_at, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit form.object.new_record? ? "Add Article" : "Update Article", class: "bg-gold-500 hover:bg-gold-600 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Articles', articles_path %>
  </nav>
  <h1 class="font-serif text-4xl">Edit '<%= @article.title %>'</h1>
</div>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<% title "Articles" %>

<div class="flex items-start">
  <h1 class="font-serif text-4xl">Articles</h1>
  <% if user_signed_in? %>
    <span class="mt-2 ml-4"><%= link_to 'Add New Article', new_article_path %></span>
  <% end %>
</div>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Articles', articles_path %>
  </nav>
  <h1 class="font-serif text-4xl">Add a new article</h1>
</div>

<%= form_with model: @article, url: articles_path do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :slug, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :slug, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :body, class: "block text-sm font-bold mb-2" %>
    <%= form.text_area :body, rows: 10, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :publish_at, class: "block text-sm font-bold mb-2" %>
    <%= form.datetime_field :publish_at, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit "Add Article", class: "bg-gold-500 hover:bg-gold-600 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/articles/show.html.erb
<% title @article.title %>

<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Articles', articles_path %> <span class="text-gold-400">⦂⦚</span>
  </nav>
  <h1 class="mt-2 mb-0 font-serif text-4xl"><%= @article.title %></h1>
  <span class="text-sm text-gray-500">
    <%= @article.publish_at.strftime("%B %d, %Y") %>
  </span>
  <% if user_signed_in? %>
  <span class="flex space-x-2">
    <%= link_to 'Edit', edit_article_path(@article), class: 'text-blue-500 no-thick-link' %>
    <span> &bull;</span>
    <%= button_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'text-red-500' %>
  </span>
  <% end %>
</div>

<article>
  <%= markdown @article.body %>
</article>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://joshpigford.com/articles/<%= @article.slug %>"
  },
  "headline": "<%= @article.title %>",
  "author": {
    "@type": "Person",
    "name": "Josh Pigford",
    "url": "https://joshpigford.com"
  },
  "datePublished": "<%= @article.publish_at.strftime("%Y-%m-%d") %>"
}
</script>

app/views/books/_form.html.erb
<%= form_with model: @book do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :link, class: "block text-sm font-bold mb-2" %>
    <%= form.url_field :link, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :category, class: "block text-sm font-bold mb-2" %>
    <%= form.select :category, ['Fiction', 'Nonfiction'], {}, {class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0"} %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit form.object.new_record? ? "Add Book" : "Update Book", class: "bg-gold-500 hover:bg-gold-600 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Books', books_path %>
  </nav>
  <h1 class="font-serif text-4xl">Edit '<%= @book.title %>'</h1>
</div>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<% title "Books" %>

<div class="flex items-start">
  <h1 class="font-serif text-4xl">Books</h1>
  <% if user_signed_in? %>
    <span class="mt-2 ml-4"><%= link_to 'Add New Book', new_book_path %></span>
  <% end %>
</div>
<p class="mt-0 text-lg">I go in phases with reading...sometimes consuming multiple books a month while other times taking months to read one book. This is a list of books I recommend. If Goodreads is your jam, <a href="https://www.goodreads.com/shpigford">I'm there as well</a>.</p>

<h2>Fiction</h2>
<ul>
  <% @fiction.each do |book| %>
    <li>
      <%= link_to book.title, book.link %>
    </li>
  <% end %>
</ul>

<h2>Non-Fiction</h2>
<ul>
  <% @nonfiction.each do |book| %>
    <li>
      <%= link_to book.title, book.link %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Books', books_path %>
  </nav>
  <h1 class="font-serif text-4xl">Add a new book</h1>
</div>

<%= render 'form', book: @book %>

app/views/podcasts/_form.html.erb
<%= form_with model: @podcast do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :link, class: "block text-sm font-bold mb-2" %>
    <%= form.url_field :link, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit form.object.new_record? ? "Add Podcast" : "Update Podcast", class: "bg-gold-500 hover:bg-gold-600 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Podcasts', podcasts_path %>
  </nav>
  <h1 class="font-serif text-4xl">Edit '<%= @podcast.title %>'</h1>
</div>

<%= render 'form', podcast: @podcast %>

app/views/podcasts/index.html.erb
<% title "Podcasts" %>

<div class="flex items-start">
  <h1 class="font-serif text-4xl">Podcasts</h1>
  <% if user_signed_in? %>
    <span class="mt-2 ml-4"><%= link_to 'Add New Podcast', new_podcast_path %></span>
  <% end %>
</div>
<p class="mt-0 text-lg">Here are podcasts I recommend checking out. Some publish regularly, others are short, one-off series.</p>

<ul>
  <% @podcasts.each do |podcast| %>
    <li>
      <%= link_to podcast.name, podcast.link %>
    </li>
  <% end %>
</ul>

app/views/podcasts/new.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Podcasts', podcasts_path %>
  </nav>
  <h1 class="font-serif text-4xl">Add a new podcast</h1>
</div>

<%= render 'form', podcast: @podcast %>

app/views/projects/_form.html.erb
<%= form_with model: @project do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :slug, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :slug, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :link, class: "block text-sm font-bold mb-2" %>
    <%= form.url_field :link, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :year, class: "block text-sm font-bold mb-2" %>
    <%= form.number_field :year, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-sm font-bold mb-2" %>
    <%= form.text_area :description, rows: 5, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :outcome, class: "block text-sm font-bold mb-2" %>
    <%= form.text_area :outcome, rows: 5, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="mb-4">
    <%= form.label :notes, class: "block text-sm font-bold mb-2" %>
    <%= form.text_area :notes, rows: 5, class: "appearance-none rounded w-full py-2 px-3 text-black leading-tight focus:outline-none focus:shadow-none focus:ring-0 border-0" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit form.object.new_record? ? "Add Project" : "Update Project", class: "bg-gold-500 hover:bg-gold-600 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Projects', projects_path %>
  </nav>
  <h1 class="font-serif text-4xl">Edit '<%= @project.name %>'</h1>
</div>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<% title "Projects" %>

<div class="flex items-start mb-0">
  <h1 class="font-serif text-4xl">Projects</h1>
  <% if user_signed_in? %>
    <span class="mt-2 ml-4"><%= link_to 'Add New Project', new_project_path %></span>
  <% end %>
</div>
<p class="mt-0 text-lg">I&apos;ve worked on (and continue to work on) an absurd number of things. Current tally? <%= @projects.length %> projects.</p>


<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Started</th>
      <th>Description</th>
      <th>What Happened</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td class="px-2 py-3">
          <%= link_to project.name, project_path(project) %>
        </td>
        <td><%= project.year %></td>
        <td><%= project.description %></td>
        <td><%= project.outcome %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Projects', projects_path %>
  </nav>
  <h1 class="font-serif text-4xl">Add a new project</h1>
</div>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<% title @project.name %>

<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Projects', projects_path %> <span class="text-gold-400">⦂⦚</span>
  </nav>
  <h1 class="flex items-center mt-2 mb-0 font-serif text-4xl gap-x-3"><%= @project.name %> <span class="text-gray-400">⦚</span> <span class="text-lg text-gray-200"><%= @project.year %></span></h1>
  <p class="mt-1 text-lg"><%= @project.description %></p>
  <% if user_signed_in? %>
  <span class="flex space-x-2">
    <%= link_to 'Edit', edit_project_path(@project), class: 'text-blue-500 no-thick-link' %>
    <span> &bull;</span>
    <%= button_to 'Delete', project_path(@project), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'text-red-500' %>
  </span>
  <% end %>
</div>

<% if @project.notes.present? %>
  <div>
    <h2 class="mt-8 mb-0 font-serif text-2xl">A bit more background</h2>
    <p class="mt-1 text-lg"><%= @project.notes %></p>
  </div>
<% end %>

<h2 class="mt-8 mb-0 font-serif text-2xl">What happened?</h2>
<p class="mt-1 text-lg"><%= @project.outcome %></p>

<% if @project.link.present? %>
  <p class="mt-8"><%= link_to "Check it out →", @project.link, target: "_blank", rel: "noopener noreferrer", class: "text-2xl" %></p>
<% end %>

app/views/toys/index.html.erb
<% title "Toys" %>

<div class="flex items-start mb-0">
  <h1 class="font-serif text-4xl">Toys</h1>
  <% if user_signed_in? %>
    <span class="mt-2 ml-4"><%= link_to 'Add New Toy', new_toy_path %></span>
  <% end %>
</div>
<p class="mt-0 text-lg">I started collecting designer toys back in 2004. Eventually, my little hobby turned into an <a href="https://joshpigford.com/projects/fugitive-toys">actual toy store</a> that my wife and I started in 2006, and then sold in 2009. My collection isn't quite what it was back then, but in the past few years I've started actively collecting again. This is a place for me to show off that collection!</p>

app/views/toys/new.html.erb
<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Toys', toys_path %>
  </nav>
  <h1 class="font-serif text-4xl">Add a new toy</h1>
</div>

<%= render 'form', toy: @toy %>

app/views/toys/show.html.erb
<% title @toy.name %>

<div>
  <nav aria-label="breadcrumb">
    <%= link_to 'Toys', toys_path %> <span class="text-gold-400">⦂⦚</span>
  </nav>
  <h1 class="flex items-center mt-2 mb-0 font-serif text-4xl gap-x-3"><%= @toy.name %></h1>
  <% if user_signed_in? %>
  <span class="flex space-x-2">
    <%= link_to 'Edit', edit_toy_path(@toy), class: 'text-blue-500 no-thick-link' %>
    <span> &bull;</span>
    <%= button_to 'Delete', toy_path(@toy), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'text-red-500' %>
  </span>
  <% end %>
</div>

<div class="flex items-start space-x-12">
  <div class="w-3/5 max-h-[800px] relative overflow-hidden" data-controller="image-rotator">
    <div class="absolute z-10 hidden text-3xl text-black stop-icon top-8 right-5">⏹</div>
    <% @toy.images.each_with_index do |image, index| %>
      <p class="<%= 'hidden' unless index.zero? %>" data-image-rotator-target="image">
        <%= image_tag url_for(image.variant(resize_to_fill: [800, 800])), class: "w-full h-auto max-h-[800px] object-contain transition-opacity duration-500 ease-in-out rounded-md" %>
      </p>
    <% end %>
  </div>
  <table class="w-2/5">
    <tr> 
      <th>Artist</th>
      <td><%= @toy.artist %></td>
    </tr>
    <tr> 
      <th>Manufacturer</th>
      <td><%= @toy.manufacturer %></td>
    </tr>
    <tr> 
      <th>Platform</th>
      <td><%= @toy.platform %></td>
    </tr>
    <% if @toy.series.present? %>
    <tr> 
      <th>Series</th>
      <td><%= @toy.series %></td>
    </tr>
    <% end %>
    <tr> 
      <th>Size</th>
      <td><%= @toy.size %>"</td>
    </tr>
    <tr> 
      <th>Color</th>
      <td><%= @toy.color %></td>
    </tr>
    <tr> 
      <th>Released</th>
      <td><%= @toy.release_date.strftime('%Y') %></td>
    </tr>
    <% if @toy.original_price.present? %>
    <tr> 
      <th>Original Price</th>
      <td><%= @toy.original_price %></td>
    </tr>
    <% end %>
  </table>
</div>