config/routes.rb
Rails.application.routes.draw do
  resource :registration
  resource :session

  resources :articles
  resources :projects
  resources :investments
  resources :podcasts
  resources :books
  resources :toys
  
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :slug, :body, :publish_at, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/investment.rb
class Investment < ApplicationRecord
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  validates :name, :link, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :slug, :year, :description, :outcome, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end
end

app/models/toy.rb
class Toy < ApplicationRecord
  has_many_attached :images

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  normalizes :email, with: -> (email) { email.strip.downcase }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @fiction = Book.where(category: "Fiction").order(title: :asc)
    @nonfiction = Book.where(category: "Nonfiction").order(title: :asc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(slug: params[:id])

    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :link, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @toys = Toy.all.order(:platform, :name)
  end

  def new
    @toy = Toy.new
  end

  def show
    @toy = Toy.find_by(id: params[:id])
    @full_width = true
  end

  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to @toy
    else
      render :new
    end
  end

  private

  def toy_params
    params.require(:toy).permit(:name, :description, :artist, :manufacturer, :release_date, :size, :platform, :color, :series, :original_price, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_symbol
    symbols = %w[⦂⦂ ⦿ ⊛ ⊚ ⊙ ⦚ ⟁ ⦂⦚ ⌇ ⦚⦚ ⌁ ⌀ ⌮ ⌬ ⌭ ⌯ ⌰ ⌱ ⌲ ⌳ ⌴ ⌵ ⌽ ⌾ ⌿ ⍀ ⍅ ⍆ ⍉ ⍊ ⍋ ⍎ ⍏ ⍑ ⍒ ⍕ ⍖ ⍘ ⍙ ⍚ ⍛ ⍜ ⍝ ⍡ ⍢ ⍣ ⍤ ⍥ ⍦ ⍧ ⍨ ⍩ ⍪ ⍫ ⍬ ⍭ ⍮ ⍱ ⍲ ⍻ ⍼ ⍽ ⍾ ⍿ ⟀ ⟁ ⟂ ⟃ ⟄ ⟅ ⟆ ⟇ ⟈ ⟉ ⟊ ⟌ ⟐ ⟑ ⟒ ⟓ ⟔]
    symbols.sample
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      space_after_headers: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def description(page_description)
    content_for(:description) { page_description }
  end

  def meta_image(meta_image)
    content_for(:meta_image) { meta_image }
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark">
  <head>
    <title><%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <meta name="title" content="<%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %>">
    <meta name="description" content="<%= content_for?(:description) ? (yield(:description)) : "Josh Pigford: Dabbler. Co-founder and CEO of Maybe." %>">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="<%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %>">
    <meta property="og:description" content="<%= content_for?(:description) ? (yield(:description)) : "Josh Pigford: Dabbler. Co-founder and CEO of Maybe." %>">
    <meta property="og:image" content="<%= image_url(content_for?(:meta_image) ? yield(:meta_image) : "meta.png") %>">
    <%= yield :meta %>

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:title" content="<%= content_for?(:title) ? ("#{yield(:title)} - Josh Pigford").html_safe : "Josh Pigford" %>">
    <meta property="twitter:description" content="<%= content_for?(:description) ? (yield(:description)) : "Josh Pigford: Dabbler. Co-founder and CEO of Maybe." %>">
    <meta property="twitter:image" content="<%= image_url(content_for?(:meta_image) ? yield(:meta_image) : "meta.png") %>">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#ffe00d">
    <meta name="msapplication-TileColor" content="#ffe00d">
    <meta name="theme-color" content="#ffe00d">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body class="dark:bg-black dark:text-white">
    <% if user_signed_in? %>
      <div class="absolute top-0 right-0 px-4 py-2 text-black bg-gold-400">
        <%= button_to "Sign out", session_path, method: :delete %>
      </div>
    <% end %>
    <div class="items-start gap-4 p-8 md:flex md:py-20">
      <a href="/" class="text-6xl font-semibold text-right text-gold-500 hover:text-gold-400 w-14">&#10626;&#10650;</a>
      <div>
        <header class="mb-10 font-serif prose dark:prose-invert max-w-none">
          <h1 class="mb-3 text-6xl font-light tracking-tight">Josh Pigford</h1>

          <p class="text-xl">
            <%= link_to "Home", root_path %> / <%= link_to "Articles", articles_path %> / <%= link_to "Projects", projects_path %> / <%= link_to "Investments", investments_path %> / <%= link_to "Podcasts", podcasts_path %> / <%= link_to "Books", books_path %>
          </p>
        </header>
        <div class="font-serif prose dark:prose-invert <%= 'max-w-full w-full' if @full_width == true %>">
          <%= yield %>
        </div>
        <footer class="my-12 font-serif text-sm prose text-gray-400 dark:prose-invert">
          <p>
            This thing is <a href="https://github.com/Shpigford/joshpigford.com">open source</a>, for better or worse.
          </p>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for :meta do %>
<meta property="profile:first_name" content="Josh">
<meta property="profile:last_name" content="Pigford">
<% end %>

<div class="font-serif prose dark:prose-invert">
  <p class="text-3xl">Dabbler. Currently building <a href="https://maybe.co">Maybe</a>, the OS for your personal finances.</p>
  <p class="text-2xl">You can find me on <a href="https://twitter.com/Shpigford">Twitter</a>. I really spend far too much time there.</p>
</div>

<script type="application/ld+json">
{
  "@context": "https://schema.org/",
  "@type": "Person",
  "name": "Josh Pigford",
  "url": "https://joshpigford.com",
  "image": "https://avatar.joshpigford.com",
  "sameAs": [
    "https://twitter.com/Shpigford",
    "https://x.com/Shpigford",
    "https://joshpigford.com",
    "https://github.com/Shpigford",
    "https://www.linkedin.com/in/joshpigford/"
  ],
  "jobTitle": "CEO",
  "worksFor": {
    "@type": "Organization",
    "name": "Maybe"
  }  
}
</script>